services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # 专用连接工厂服务
  doctrine_dedicated_connection.factory:
    class: Tourze\DoctrineDedicatedConnectionBundle\Factory\DedicatedConnectionFactory
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@Tourze\Symfony\RuntimeContextBundle\Service\ContextServiceInterface'
      - '@?logger'
    tags:
      - { name: kernel.reset, method: closeCurrentContext }
    public: true  # Make it public for testing

  # 创建别名方便使用
  Tourze\DoctrineDedicatedConnectionBundle\Factory\DedicatedConnectionFactory:
    alias: doctrine_dedicated_connection.factory
    public: false
