name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        symfony: [6.4.*, 7.0.*]
        exclude:
          - php: 8.1
            symfony: 7.0.*

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer require "symfony/framework-bundle:${{ matrix.symfony }}" --no-update
        composer update --prefer-dist --no-progress

    - name: Run tests
      run: vendor/bin/phpunit --coverage-text

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src --level=5